ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(Picsello.Repo, :manual)
Picsello.Sandbox.PidMap.start()
{:ok, _} = Application.ensure_all_started(:wallaby)
Application.put_env(:wallaby, :base_url, PicselloWeb.Endpoint.url())
