name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_1-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "1"
      partitions: "6"
    secrets: inherit
  test_2-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "2"
      partitions: "6"
    secrets: inherit
  test_3-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "3"
      partitions: "6"
    secrets: inherit
  test_4-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "4"
      partitions: "6"
    secrets: inherit
  test_5-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "5"
      partitions: "6"
    secrets: inherit
  test_6-6:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "6"
      partitions: "6"
    secrets: inherit