name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_1-4:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "1"
      partitions: "4"
    secrets: inherit
  test_2-4:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "2"
      partitions: "4"
    secrets: inherit
  test_3-4:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "3"
      partitions: "4"
    secrets: inherit
  test_4-4:
    uses: ./.github/workflows/reusable_elixir.yml
    with:
      partition: "4"
      partitions: "4"
    secrets: inherit