name: slack

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  MSG_MINIMAL: ref,commit
  SLACK_USERNAME: Picsello CI
  SLACK_ICON_EMOJI: ':camera:'
  SLACK_MESSAGE: ${{github.event.workflow_run.html_url}}

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: green
        SLACK_TITLE: ':rocket: build passed :rocket:'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: red
        SLACK_TITLE: ':skull: build failed :skull:'
