name: slack

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ':rocket: [build passed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: log available stuffs
      run: echo '${{toJSON(github.event.workflow_run)}}'
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: ':skull: [build failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})'
